### ISSUE TITLE
eventLoopGroupProvider provider for async http client

### ISSUE THREAD

**Issue by thoven87** [mochidev/swift-webpush#39]
Thanks for much for putting this great library together. I have been testing it for a few days now. 

I come to the conclusion that `eventLoopGroupProvider` should not be a required parameter since it's only used the async-http-client. Should WebPushManager take in an instance of the http client instead? In [Hummingbird](https://github.com/hummingbird-project/hummingbird) one can create a single HTTPClientService that gets shared amongst all libraries that needs an instance of the http client.

Please let me know if this is a welcome change as it is also a  breaking change. I can a PR out if needed.

I think [this deinit](https://github.com/mochidev/swift-webpush/blob/main/Sources/WebPush/WebPushManager.swift#L137) can be replaced with the service lifecycle. An example of the service life cycle can be seen [here](https://github.com/hummingbird-project/hummingbird-examples/blob/main/proxy-server/Sources/App/Application%2Bbuild.swift#L50) we would simply add WebPushManager as a [service](https://github.com/hummingbird-project/hummingbird-examples/blob/main/proxy-server/Sources/App/Application%2Bbuild.swift#L46) graceful shutdown would be handle cleanly 

https://github.com/swift-server/swift-service-lifecycle

**Comment by dimitribouniol** [comment]
Just because Hummingbird provides an HTTPClient, does not mean it should be shared by the WebPushManager — it may have a very different set of expectations than the one provided after all (namely HTTP/2 support, no TLS client overrides, etc…). Not to mention, pipelining will likely be tweaked in the near future, so a shared HTTP client may likely interrupt this process from working smoothly.

The purpose of `eventLoopGroupProvider` is to share the actual resource that needs to be shared throughout the process: the NIO event loop group. By default, the shared event loop group is used, so the parameter is not even required as a result, but if you did customize it, you can ask your [Hummingbird Application's `eventloopGroup`](https://github.com/hummingbird-project/hummingbird/blob/169b1ccf7ba1841fa58f66b6d710ec626c720083/Sources/Hummingbird/Application.swift#L58) for a value to use:
```swift
let manager = WebPushManager(
    vapedConfiguration: config,
    backgroundActivityLogger: logger,
    eventLoopGroupProvider: .shared(application.eventloopGroup)
)
```

The purpose of the deinit is to facilitate usage when swift-service-lifecycle is not used (mostly because there was a ton of boilerplate in tests, and in existing Vapor apps). `WebPushManager` is in fact a compatible Service that can be installed alongside the rest of the ones you use.

If you run into any integration issues with what I mentioned above, please let me know!

**Comment by thoven87** [comment]
> Just because Hummingbird provides an HTTPClient, does not mean it should be shared by the WebPushManager — it may have a very different set of expectations than the one provided after all (namely HTTP/2 support, no TLS client overrides, etc…). Not to mention, pipelining will likely be tweaked in the near future, so a shared HTTP client may likely interrupt this process from working smoothly.
> 
> The purpose of `eventLoopGroupProvider` is to share the actual resource that needs to be shared throughout the process: the NIO event loop group. By default, the shared event loop group is used, so the parameter is not even required as a result, but if you did customize it, you can ask your [Hummingbird Application's `eventloopGroup`](https://github.com/hummingbird-project/hummingbird/blob/169b1ccf7ba1841fa58f66b6d710ec626c720083/Sources/Hummingbird/Application.swift#L58) for a value to use:
> 
> ```swift
> let manager = WebPushManager(
>     vapedConfiguration: config,
>     backgroundActivityLogger: logger,
>     eventLoopGroupProvider: .shared(application.eventloopGroup)
> )
> ```
> 
> The purpose of the deinit is to facilitate usage when swift-service-lifecycle is not used (mostly because there was a ton of boilerplate in tests, and in existing Vapor apps). `WebPushManager` is in fact a compatible Service that can be installed alongside the rest of the ones you use.
> 
> If you run into any integration issues with what I mentioned above, please let me know!

Thanks for such a detail response. Hummingbird does not provide an HTTPClient by default. It makes use of the swift service life cycle. Unless, the HTTPClient's configuration needs changes inside WebPushManager which I don't think it does today. An instance of the Client should be passed instead. I don't any strong opinions of requiring an `eventLoopGroupProvider` provider or not. Would provide another init definition which takes in an instance of HTTPClient.shared suffice?

How does one handle graceful shutdown with the current implementation? Since the eventLoopGroupProvider is not even required?

**Comment by dimitribouniol** [comment]
There is a new initializer that takes an `unsafeHTTPClient:` if you _really_ want this, but generally you shouldn't need it. Feel free to re-open this or a new issue if that's not enough!
