### ISSUE TITLE
Remove Foundation

### ISSUE THREAD

**Issue by t089** [mochidev/swift-webpush#54]
Or replace with FoundationEssentials to avoid unnecessary large binary size on Linux.

**Comment by dimitribouniol** [comment]
So I made the change here, but unfortunately none of the dependencies this relies on (swift-crypto, swift-no, async-http-client…) do the same, so not sure it'll make much of a difference 😔

**Comment by t089** [comment]
We will get there 😀 thanks for tackling this!

**Comment by t089** [comment]
Regarding `swift-nio`. I would suggest to ditch `NIOFoundationCompat` and pull in the 1,2 methods you need directly to here and make them only import `FoundationEssentials`. Unfortunately, `NIOFoundationCompat` depends on API that is not available in `FoundationEssentails` :(

**Comment by dimitribouniol** [comment]
Mind you, I'm not using SwiftNIO directly, so that's not really feasible. Pretty much everyone who will be using this package will also be using SwiftNIO in some form, so I don't really feel like diluting the surface this package touches will make any difference at all. Once package traits become available, I can explore a more limited "Toolbox" style of package that drops the networking aspects completely, but a) I don't know who actually needs this, and b) its not really a design goal at the moment (which is to provide a comprehensive solution for adding WebPush to an existing server app)

**Comment by t089** [comment]
Actually, you are not using `NIOFoundationCompat`, so `swift-nio` is not a problem at all (NIO does not depend on `Foundation` at all).

**Comment by dimitribouniol** [comment]
Unfortunately, my main dependencies of AsyncHTTPClient and SwiftCrypto _do_ `import Foundation` all over the place. Getting rid of either of them is likely to either make this package much more difficult to maintain, or much less capable. Not to mention, these are packages almost every swift-server-based linux user is already using, so not really a design goal either way.

**Comment by t089** [comment]
Step 1: https://github.com/apple/swift-crypto/pull/317
